### ISSUE TITLE
合成的源代码

### ISSUE THREAD

**Issue by guozhihua2** [bcmi/Awesome-Image-Composition#2]
各位大佬，合成的源代码什么时候可以提交上来呢？

**Comment by ustcnewly** [comment]
是指demo的代码吗？demo的代码近期不开源，实现各个功能的代码可以从其他github仓库找到。

**Comment by guozhihua2** [comment]
感谢作者百忙之中的回复，确实对这个端到端的demo代码很好奇，其他代码是其他论文的开源代码。希望后续可以开源demo的代码，因为那个网站的功能只限于参考图片，没法用我们自己的数据哈。



---原始邮件---
发件人: "Li ***@***.***&gt;
发送时间: 2023年9月4日(周一) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bcmi/Awesome-Image-Composition] 合成的源代码 (Issue #2)




 
是指demo的代码吗？demo的代码近期不开源，实现各个功能的代码可以从其他github仓库找到。
